### ISSUE TITLE
Deployments page, and reports

### ISSUE THREAD

**Issue by smwoodman** [SWFSC/glider-lab-manual#5]
When looking at the home page today, I felt that rather than referencing deployments on the home page, it could make sense to make a 'Deployments' page that appears in the Sidebar at the same level as and right below 'Shared values'. I.e.:
``` yaml
...
contents:
      - href: index.qmd
        text: Home
      - href: content/shared-values.qmd
        text: Shared Values
      - href: content/deployments.qmd
        text: Deployments
      - section: "Glider Lab"...
```

This page would be all about: listing past/current deployments, including info about:

- accessing public deployment data from IOOS's ERDDAP
- Embedded map, or some link to current deployed glider locations
- ..more!

Creating this issue to keep this in mind, and as a place to put more ideas.
